### ISSUE TITLE
Add Up Button In SendFormsActivity and WifiActivity

### ISSUE THREAD

**Issue by iadeelzafar** [opendatakit/skunkworks-crow#108]
### Describe the feature:

* Adding an up button in SendFormsActivity and WifiActivity.
* What you guys think? @shobhitagarwal1612 @lakshyagupta21 

### Screenshot:

 <img src = "https://user-images.githubusercontent.com/36811908/53101785-42710300-354c-11e9-9a68-f57ded0707a8.gif" height="700" width="394">

**Comment by shobhitagarwal1612** [comment]
Can you please describe the issue?

**Comment by iadeelzafar** [comment]
@shobhitagarwal1612 It's a feature request. Adding an up button to these activities will help the user go back to the parent activity even at times when the user has opened these fragments from a notification. In such cases, if there's no up button and user presses back button, he/she will be taken back to the place(for e.g. a third party app) from where he opened that fragment.

**Comment by lakshyagupta21** [comment]
No "third party" app opens share but yes adding up button will help the user navigate the screens.

**Comment by iadeelzafar** [comment]
@lakshyagupta21 Alright. I'll make a PR for this soon.

**Comment by iadeelzafar** [comment]
@lakshyagupta21 Could you please guide me how I can use this app as a user(like how it's meant to be used because currently all I see in the app is just a widgets form which I don't know what to do with it) so that I would be able to see how this app could be improved. Thank you!

**Comment by lakshyagupta21** [comment]
Have you tried [Collect](https://play.google.com/store/apps/details?id=org.odk.collect.android&hl=en), please try if you haven't then and read about [Collect](https://play.google.com/store/apps/details?id=org.odk.collect.android&hl=en) if you want more information about it. This app is just an addon to Collect. After trying both the apps then maybe you can come up with some feature ideas or improvements.

**Comment by iadeelzafar** [comment]
Thank you. I'll definitely give it a shot.

**Comment by Chromicle** [comment]
Hello @iadeelzafar update it to settings preference also so no other issue will raise about this type of problem

**Comment by iadeelzafar** [comment]
@opendatakit-bot claim

**Comment by iadeelzafar** [comment]
@opendatakit-bot claim --force
