### ISSUE TITLE
Toast message or snack bar does not appear upon exiting the app

### ISSUE THREAD

**Issue by ghost** [opendatakit/skunkworks-crow#118]
## DESCRIPTION
**Actual Behaviour**
If the user clicks the back button, the app exits without showing the Toast message or snack bar
**Expected Behaviour**
Toast or snack bar should appear upon clicking back button twice.
**Steps to reproduce it**
Click back button from the app's share screen

**Comment by Chromicle** [comment]
Can I work on this, thank you!

**Comment by lakshyagupta21** [comment]
Why do you think this feature is required?

**Comment by Chromicle** [comment]
@lakshyagupta21 because when using a multipage Android app, it is all too easy to accidentally back your way out of the app this feature will remove that issue know

**Comment by Chromicle** [comment]
@lakshyagupta21 can I add the new issue I caught which is important

**Comment by lakshyagupta21** [comment]
@Chromicle I've seen this feature in apps which contains tabs on the home screen. And we don't have one on our home screen, so I don't think we need this unless some user reports this issue.

**Comment by Chromicle** [comment]
@lakshyagupta21 Yeah ! before reporting that type of issue if we add means it gives good user experiance.
Or else we can put the Toast message that he/she exited out of the app so user can know he exited the app.
hopes it useful for good user experiance.

**Comment by Chromicle** [comment]
@lakshyagupta21 I had a onother doubt that can we add splash screen and sharing of app to others with inviting link

**Comment by lakshyagupta21** [comment]
For splash screen and sharing app invitation link first we need to bring this app to a release state then we will think about these ideas, for now, these are of very low priority and for splash screen, we need to finalize the app icon then we can go ahead with the splash screen.

**Comment by lakshyagupta21** [comment]
Even I'm not convinced with adding a toast or snack bar for the back button, even collect doesn't have this feature, maybe @shobhitagarwal1612 can help us here.

**Comment by tavishjain** [comment]
Yes, we can consider adding a Snackbar while exiting

**Comment by tavishjain** [comment]
Yes, we can consider adding a Snackbar while exiting

**Comment by shobhitagarwal1612** [comment]
@tavishjain Thank you for starting this conversation. But I also don't feel the need for this right now. If you are looking for something to work on, maybe this issue will look exciting to you https://github.com/opendatakit/skunkworks-crow/issues/203
