### ISSUE TITLE
Add list item divider to filled forms and blank forms

### ISSUE THREAD

**Issue by ghost** [opendatakit/skunkworks-crow#121]
## Description
Currently, there are no list item dividers to the filled forms and blank forms
add the list item dividers to filled forms and blank forms 
as these dividers are often used to separate different list items and specify the boundaries of each list item layout which is clickable. This holds good for positive user experience.

**Comment by Chromicle** [comment]
can I work on this thankyou!

**Comment by lakshyagupta21** [comment]
Sure @Chromicle go ahead maybe card item would be a good idea for better user experience.

**Comment by Chromicle** [comment]
hello @lakshyagupta21 due to some reasons I can not log in my GitHub account I tried to get back my account for up to 7 hours but it does not possible so, I created the new account named @chromicle only I will send the pull request now

**Comment by jddeep** [comment]
@lakshyagupta21 I have got experience in UX designing. You can take a look at my profile. Can you kindly assign it to me? I shall work on it.

**Comment by lakshyagupta21** [comment]
@jddeep Sorry PR is already raised for this issue and @Chromicle is already working on it. You can pick up any other issue which is not already taken.

**Comment by shobhitagarwal1612** [comment]
@jddeep Would you like to give this issue https://github.com/opendatakit/share/issues/117 a try?

**Comment by Chromicle** [comment]
But on #117 @Dreamyphobic is working know

**Comment by shobhitagarwal1612** [comment]
More designs will provide more options to choose an icon from. :smiley:

**Comment by Chromicle** [comment]
Yeah @shobhitagarwal1612 it is correct can I also suggest
