### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#129]
#### Problem description
The project has been renamed to `skunkworks-crow` since it is still unreleased and an experimental project. README also needs to be updated. `Share` should be replaced with `skunkworks-crow`

**Comment by iamvasuh** [comment]
i will be happy to do this.

**Comment by iamvasuh** [comment]
done and PR

**Comment by Chromicle** [comment]
@iamvasuh before making PR make sure that it assigned to you😁

**Comment by shobhitagarwal1612** [comment]
@iamvasuh Please claim the issue by commenting `@opendatakit-bot claim`

**Comment by iamvasuh** [comment]
@opendatakit-bot claim

**Comment by iamvasuh** [comment]
u can close this issue now @opendatakit-bot
