### ISSUE TITLE
Rename project directory

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#130]
#### Problem description
The project directory needs to be renamed from `share_app` to `skunkworks_crow`

**Comment by iamvasuh** [comment]
i would like to work on this.

**Comment by shobhitagarwal1612** [comment]
Hey @iamvasuh. You are already working on https://github.com/opendatakit/skunkworks-crow/pull/131. Maybe someone else can take on this one until you are working on that.

**Comment by iamvasuh** [comment]
ok no problem

**Comment by prajurock** [comment]
Can i work on this issue?

**Comment by shobhitagarwal1612** [comment]
Yes, please. You can claim the issue by commenting `@opendatakit-bot claim` below

**Comment by prajurock** [comment]
@opendatakit-bot claim
