### ISSUE TITLE
Change the default hotspot name

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#136]
#### Software and hardware versions 
Devices having Android version < 8
#### Problem description
For devices having android version < 8, by default hotspot name is set to ODK-SHARE-odk-share which should be changed to ODK-SKUNKWORKS-odk-skunkworks.
#### Steps to reproduce the problem
1. Press 'Send'
2. Select the forms
3. Press 'Send'
4. Start Hostpot
5. Default name would show ODK-SHARE-odk-share
#### Expected behavior
Default name should be changed to ODK-SKUNKWORKS-odk-skunkworks

**Comment by prajurock** [comment]
@lakshyagupta21 i would like to work

**Comment by prajurock** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
@lakshyagupta21 Is there a specific reason as to why we can't name the hotspot with a shorter name, like `skunkworks-crow`?

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 We can have skunkworks-crow. My idea is to have something in prefix every time a user creates a hotspot so that nearby devices can uniquely identify the network created by the skunkwork-crow app.
