### ISSUE TITLE
Clean up casting.

### ISSUE THREAD

**Issue by moksh-mahajan** [opendatakit/skunkworks-crow#138]
#### Problem description
One of the things that google announce in IO 2017 is something that’s called ‘cast away’ :). Android developer don’t have to do a manual casting for findViewById(). It’s a simple change. But for a seasoned programmer, a clean code like this can make you very happy and it helps with your coding mood :)

**Comment by lakshyagupta21** [comment]
@moksh-mahajan Thanks for raising an issue.
 Can you describe more about the issue and how are you going to solve it? Some links and references would be helpful.

**Comment by moksh-mahajan** [comment]
@lakshyagupta21 Though it can be done manually by going to all activities and deleting the redundant casting code before all findViewById () methods, but Android Studio provides an easy way to do this: https://link.medium.com/S4L8hzGZGU

**Comment by shobhitagarwal1612** [comment]
@moksh-mahajan Thanks for raising an issue but this is not required. We are using `Butterknife` for the same purpose. 

Closing this
