### ISSUE TITLE
Fix Grammatical mistakes and typos found in README.md

### ISSUE THREAD

**Issue by rohap97** [opendatakit/skunkworks-crow#142]
#### Problem description
There are some grammatical mistakes and typos in the README.md file.

#### Steps to reproduce the problem
Read the README.md file

**Comment by rohap97** [comment]
@opendatakit-bot claim

**Comment by rohap97** [comment]
@opendatakit-bot claim --force

**Comment by lakshyagupta21** [comment]
@rohap97 Before raising a PR can you describe the issue raised? What kind of grammatical mistakes and typos are there?

**Comment by rohap97** [comment]
@lakshyagupta21  Sir, There are few grammatical mistakes in the README.md file. I am pointing out one of the mistakes for your reference.

In Section 3.2 , Paragraph 7, The starting of the sentence is with "Is". It should be started with "It".
Here's the extract :-
"Is user wants to manually connect to it then the screen shows the network name so that user can connect to it by tapping on the network, and after wifi is connected it will ask for a port number which is required to create the connection."

**Comment by rohap97** [comment]
@lakshyagupta21 Sir, should I wait for Pull Request #135 to get merged with the master branch, because the issue that is fixed by Pull Request #135 still persists in my build.

**Comment by lakshyagupta21** [comment]
Don't depend on other PRs because sometimes PR needs time for reviews, changes, etc. If you both are doing the changes in the same files then also there is no issue.

**Comment by rohap97** [comment]
@lakshyagupta21 Ok Sir. I will keep that in mind
