### ISSUE TITLE
Update the compile and target SDK version.

### ISSUE THREAD

**Issue by moksh-mahajan** [opendatakit/skunkworks-crow#144]
#### Problem description
The compileSdkVersion and targetSdkVersion which are set to versions 27 and 22, respectively, must be changed to 28( Android Pie) as the latest Android APIs must be used to make use of the latest features. 

#### Steps to reproduce the problem
Go to app-level build.gradle file. Here compileSDKVersion is set to 27 and targetSDKVersion is set to 22. These should be updated to the latest versions.

#### More details
https://developer.android.com/about/versions/oreo/android-8.0-migration

**Comment by moksh-mahajan** [comment]
@shobhitagarwal1612 @lakshyagupta21 Can I work on this issue?

**Comment by lakshyagupta21** [comment]
This issue is already opened #119
