### ISSUE TITLE
Addition of progress bar while scanning for wifi.

### ISSUE THREAD

**Issue by moksh-mahajan** [opendatakit/skunkworks-crow#146]
#### Problem description
When clicking on Scan Wifi button on Connect to Wifi screen, it shows a simple TextView containing text "Scanning. Please wait". My idea is to include a progressBar or progressDialog for this to enhance the user experience.
![20190301_125301](https://user-images.githubusercontent.com/36201975/53622875-3f97a180-3c21-11e9-9f65-061c3c34f12a.gif)

#### Steps to reproduce the problem
Make sure you have Wifi enabled.
Click on Receive button.
Click on Scan Wifi button.

A simple text will be shown "Scanning. Please wait"
#### Expected behavior
A nice progressBar or progressDialog can be shown for improving User experience.

**Comment by moksh-mahajan** [comment]
@lakshyagupta21 @shobhitagarwal1612 Can I start working on this issue?

**Comment by lakshyagupta21** [comment]
Sure go ahead,  Make sure you assign this issue to yourself first by `@opendatakit-bot claim`

**Comment by moksh-mahajan** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
A progress dialogue would be a better option in this case. Also, make sure that it works well if screen is rotated while it's being displayed

**Comment by iamvasuh** [comment]
@moksh-mahajan r u still working on this? 
if not, can I claim this issue?

**Comment by moksh-mahajan** [comment]
@opendatakit-bot unclaim

**Comment by naman653** [comment]
@opendatakit-bot claim

**Comment by naman653** [comment]
@opendatakit-bot claim --force
