### ISSUE TITLE
Adding Back button in activity

### ISSUE THREAD

**Issue by prajurock** [opendatakit/skunkworks-crow#147]
#### Software and hardware versions 
Android v8.1.0, device used Ausu Zenfone MAx M1 pro

#### Problem description
Adding Back button in activity

#### 
![screenshot_20190301-125224](https://user-images.githubusercontent.com/26791135/53623054-ea0fc480-3c21-11e9-89ec-b1a6b2602919.png)
![screenshot_20190301-125231](https://user-images.githubusercontent.com/26791135/53623056-ea0fc480-3c21-11e9-8271-9421cd043e2d.png)
![screenshot_20190301-125525](https://user-images.githubusercontent.com/26791135/53623057-eaa85b00-3c21-11e9-8d14-f34b00985fdd.png)
![screenshot_20190301-125530](https://user-images.githubusercontent.com/26791135/53623058-eaa85b00-3c21-11e9-9f1d-2df1db48254b.png)
![screenshot_20190301-125542](https://user-images.githubusercontent.com/26791135/53623059-eb40f180-3c21-11e9-8b7e-249ea0cbf488.png)

Screenshot

**Comment by prajurock** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
@prajurock, This issue is already raised in #108 and someone else is already working on that, so please close this issue.

**Comment by prajurock** [comment]
Ok.
