### ISSUE TITLE
No counter indicator for selcted ones.

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#148]
#### Problem description
In filled forms and blank forms we do not how many forms selected if there are the large number of forms user donot know how many forms he selected

#### Expected behavior
 app should says how many forms are selected to send to others

**Comment by Chromicle** [comment]
@shobhitagarwal1612  can I work on this

**Comment by moksh-mahajan** [comment]
This seems nice to work on.

**Comment by sushmita0810** [comment]
Can I work on this

**Comment by sushmita0810** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
I think @Chromicle raised this issue and he asked to work on this first, so if he is not working then maybe you can take this up.
@Chromicle are you working on this?  If yes then please claim to avoid confusion.

**Comment by Chromicle** [comment]
@lakshyagupta21 Yeah I am working on this soon I will send the PR
