### ISSUE TITLE
advice from the Android developers blog related to aspect ratios 

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#156]
The Google Play console advises that for any android app that Added support for higher Aspect ratio devices like Samsung S8.

 blog post link = [url](https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html)

additionally, update the gradle version from 4.10.1 instead of 4.4

**Comment by Chromicle** [comment]
@shobhitagarwal1612 @lakshyagupta21 can I work on this, thank you!

**Comment by shobhitagarwal1612** [comment]
Let's not add this until it is actually requested for. This project will be used by existing ODK Collect users and statistics show that they don't use very high-end phones. So closing this issue.

**Comment by Chromicle** [comment]
Hoh! When I installed this app in my friend phone to share forms I faced this issues so I added issue, if not required then its ok

**Comment by shobhitagarwal1612** [comment]
Can you answer these questions.
1. Which phone did you use? 
2. Did the warning show up in Android studio or somewhere else? 
3. Did you face any problem while running the app in the above mentioned phone?

**Comment by shobhitagarwal1612** [comment]
Also, please fill out the issue template from now on. That provides a lot of insight into the issue

**Comment by Chromicle** [comment]
> Can you answer these questions.
> 
> 1. Which phone did you use?
> 2. Did the warning show up in Android studio or somewhere else?
> 3. Did you face any problem while running the app in the above mentioned phone?

1. I use samsung J8 
2. No warning is showing in android studio but I changed the gradle to higher version for that
3. the app is not fitting to entire screen. it is showing warning in phone
