### ISSUE TITLE
Upgrade dagger dependency

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#158]
#### Problem description
We use [dagger](https://github.com/google/dagger) for injecting dependencies. The current version is 2.16. 
A new version of dagger 2 is also available (2.19).

**Comment by prajurock** [comment]
I want to work on this issue.

**Comment by shobhitagarwal1612** [comment]
Hey @prajurock. You are already working on an issue. Please finish that one before taking up any new one. https://github.com/opendatakit/skunkworks-crow/pull/152

**Comment by iamvasuh** [comment]
can i work on this? @shobhitagarwal1612 
@lakshyagupta21

**Comment by iamvasuh** [comment]
@opendatakit-bot claim
