### ISSUE TITLE
Update RxJava 2 dependency

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#159]
Problem description
[RxJava 2](https://github.com/ReactiveX/RxJava) dependency should be updated.

**Comment by Chromicle** [comment]
Can I work on this @shobhitagarwal1612

**Comment by shobhitagarwal1612** [comment]
Yeah sure, go ahead.

**Comment by Chromicle** [comment]
can I update Rx android also @shobhitagarwal1612

**Comment by Chromicle** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
You can't claim more than one issue at a time. @opendatakit-bot is trained to prevent assigning multiple issues to a single contributor simultaneously.

**Comment by Chromicle** [comment]
Oh! I will make the PR now itself so I can prevent that
