### ISSUE TITLE
Extra spacing present in Filled forms tab

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#164]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
There is some extra spacing present above the item separator in filled forms tab.
#### Steps to reproduce the problem
1. Tap on `Send`
2. Open `Filled forms` tab 
#### Expected behavior
The extra spacing should not be present. Open `Blank Forms` tab to see the actual spacing.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
![1](https://user-images.githubusercontent.com/18495162/53687301-06624d00-3d59-11e9-944a-11aa64a95f2b.png)
![2](https://user-images.githubusercontent.com/18495162/53687302-082c1080-3d59-11e9-842a-d6866ab8797e.png)

**Comment by sushmita0810** [comment]
@opendatakit-bot claim

**Comment by sushmita0810** [comment]
I think that this problem might due to some error in InstanceList.java class 
Here I don't see any effect on the app when I make changes to onCreate class in it.
In the onCreate class when I am doing any change in Linear Layout manager like I changed the orientation from vertical to horizontal no changes occur in my android app.

**Comment by lakshyagupta21** [comment]
I don't understand your issue, what change are you trying to make?

**Comment by lakshyagupta21** [comment]
If you would see `list_item_checkbox.xml` file which is used as an item layout for filled form, there are two text view present which we never used in filled form tab so the extra spacing is because of those two items, if you can change their visibility to GONE then this extra spacing will be removed.
