### ISSUE TITLE
tabs appear too close on rotation

### ISSUE THREAD

**Issue by iamvasuh** [opendatakit/skunkworks-crow#173]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
when on rotating the screen, the two tabs "Filled Forms" and "Blank Forms" appear too close.

#### Steps to reproduce the problem
rotate the screen and tap on the "Send" button

#### Expected behaviour
both the tabs should be in a uniform space to each other

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
![tabs](https://user-images.githubusercontent.com/42612183/53713755-fe4a0080-3e71-11e9-811b-58c18e7ead4d.jpeg)

**Comment by lakshyagupta21** [comment]
@iamvasuh Please always fill the template of an issue, do not leave it blank.

**Comment by iamvasuh** [comment]
> @iamvasuh Please always fill the template of an issue, do not leave it blank.

done
