### ISSUE TITLE
Improve title of Open Source Licenses

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#176]
#### Software and hardware versions 
Moto G5 Plus, Android 9.

#### Problem description
Title of open source licenses screen is not correct on android 9, 

#### Steps to reproduce the problem
1. In the overflow menu from the main screen, tap 'about'
2. Tap 'open source libraries / licenses'

See that the menu shows the file URI.

#### Expected behavior
Should be `Open Source Licenses` instead

#### Other information 
Screenshot:
![image](https://user-images.githubusercontent.com/8918023/53854801-e2b93400-3ff0-11e9-96b4-79cdd19a618b.png)

This bus is similar to https://github.com/opendatakit/collect/issues/2397.

**Comment by rohap97** [comment]
@shobhitagarwal1612 Sir, Can I work on this?

**Comment by rohap97** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
@rohap97 Please do not claim a new issue until the last claimed issue is resolved or you have unclaimed it. This gives other contributors an equal opportunity to contribute to the project.

**Comment by rohap97** [comment]
@shobhitagarwal1612 Ok Sir, I will make sure this doesn't happen again.

**Comment by rohap97** [comment]
@opendatakit-bot claim
