### ISSUE TITLE
No space between left margin and title in action bar

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#177]
#### Software and hardware versions 
Moto G5 Plus, Android 9

#### Problem description
There is no space between title name and left margin in action bar

#### Steps to reproduce the problem
Open any screen and notice the action bar

#### Expected behavior
Space between the title and left margin in all of the screens

#### Other information 
Screenshot:
![image](https://user-images.githubusercontent.com/8918023/53855421-8dcaed00-3ff3-11e9-8c5f-ef45b02053bb.png)

**Comment by rohap97** [comment]
@shobhitagarwal1612 Sir, Can I work on this?

**Comment by Chromicle** [comment]
@rohap97 as you asked for #176 I will work on this 
@shobhitagarwal1612 can I do this

**Comment by rohap97** [comment]
@Chromicle, @shobhitagarwal1612  I have already fixed this issue. Generating Pull Request for the same. If my Pull Request isn't up to standards, @Chromicle you are welcome to fix this.

**Comment by rohap97** [comment]
@opendatakit-bot --claim

**Comment by rohap97** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
@rohap97 Please do not claim a new issue until the last claimed issue is resolved or you have unclaimed it. This gives other contributors an equal opportunity to contribute to the project.

**Comment by Chromicle** [comment]
@shobhitagarwal1612 can I submit the PR for this

**Comment by rohap97** [comment]
@shobhitagarwal1612 Ok sir, I will make sure it doesn't happen again.

**Comment by naman653** [comment]
@opendatakit-bot claim

**Comment by syedabbashussainnaqvi** [comment]
@shobhitagarwal1612 I will like to do work on this issue.
