### ISSUE TITLE
no action takes place on tapping the buttons

### ISSUE THREAD

**Issue by iamvasuh** [opendatakit/skunkworks-crow#184]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
When tapped on "Send" and "Select all", no action takes place.

#### Steps to reproduce the problem

![sent](https://user-images.githubusercontent.com/42612183/53949936-1d09fa80-40f1-11e9-88a9-343c8df4a869.gif)

#### Expected behavior
Maybe some activity can be associated with the respective buttons **OR**
 it can be removed from there.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by iamvasuh** [comment]
@shobhitagarwal1612  @lakshyagupta21  should I remove it OR add some activity with it ?

**Comment by iamvasuh** [comment]
@shobhitagarwal1612  @lakshyagupta21  can u plz take one glance at this issue?
I wanted to have an opinion regarding this issue.

**Comment by shobhitagarwal1612** [comment]
Hey @iamvasuh. Thanks for filing an issue and describing it so well.

This clearly looks like a regression due to one of the recent PRs. The buttons should not show up in `Sent` tab at all. Please remove it

**Comment by iamvasuh** [comment]
thank u @shobhitagarwal1612 for the opinion.
working on it.
