### ISSUE TITLE
Update checkstyle plugin

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#192]
#### Problem description
We haven't upgraded the `checkstyle` plugin for quite some time. Now, we should use the latest version to include all of the new features added recently

#### Steps to reproduce the problem
Not an issue, code maintenance

#### Expected behavior
`quality.gradle` contains the configuration for `checkstyle` plugin, that should be upgraded. All of the introduced modules should be added to `checkstyle.xml`

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by iamvasuh** [comment]
@shobhitagarwal1612 @lakshyagupta21 i would like to work on this.

**Comment by iamvasuh** [comment]
@opendatakit-bot claim

**Comment by iamvasuh** [comment]
@shobhitagarwal1612 @lakshyagupta21 I have updated the **_checkstyle_** version from **7.6.1** to **8.18** which is the latest one right now.
Apart from that , in the **_checkstyle.xml_** I have added the modules which are used in **_google.xml_** also. I want to ask whether this approach is right or not?

**Comment by lakshyagupta21** [comment]
We've to see what all modules we require for this project, I request you to raise a PR then we can discuss on the modules further.

**Comment by iamvasuh** [comment]
ok i will just do it.

**Comment by iamvasuh** [comment]
@opendatakit-bot unclaim

**Comment by jhbiggs** [comment]
Is this issue still open?  It looks like the plugin was updated above.

**Comment by lakshyagupta21** [comment]
Hi @jhbiggs , you can claim this issue by typing `@opendatakit-bot claim`

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Hie @lakshyagupta21 @shobhitagarwal1612, I would like to work on this issue, but I cannot claim it.
