### ISSUE TITLE
Update pmd plugin

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/skunkworks-crow#193]
#### Problem description
We haven't upgraded the `pmd` plugin for quite some time. Now, we should use the latest version to include all of the new features added recently

#### Steps to reproduce the problem
Not a bug, code maintenance

#### Expected behavior
`quality.gradle` contains the configuration for `pmd` plugin, that should be upgraded. All of the introduced modules should be excluded by adding them to `pmd-ruleset.xml`

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by Chromicle** [comment]
that means before there are so many exclude are there that should be removed right when I do that Circle Ci is passed

**Comment by shobhitagarwal1612** [comment]
It means that, after upgrading the plugin it is highly likely that the Circle CI build will fail due to the added checks. Since the scope of this issue is just to update the plugin, so the checks which are causing the build to fail must be excluded for now

**Comment by jhbiggs** [comment]
Hi, I'd like to work on this issue.  I believe I've updated PMD and have looked at the rule exclusions.  I have some questions about them, though.  Is there someone there who could answer them?

**Comment by SaumiaSinghal** [comment]
Hie @shobhitagarwal1612! I would like to work on this issue. Can I claim it, if no one else is working on it?

**Comment by SaumiaSinghal** [comment]
Hie @shobhitagarwal1612, @lakshyagupta21, I changed the PMD plugin version, and have worked out the exclusions as well. However, I am getting 500+ PMD rule violations:/

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by naman653** [comment]
@opendatakit-bot claim

**Comment by Chromicle** [comment]
Hello @naman653  as @SaumiaSinghal took this issue and it is not yet reviewed so, do not work on the issues like this
