### ISSUE TITLE
Set up top navigation(up button) 

### ISSUE THREAD

**Issue by udhay24** [opendatakit/skunkworks-crow#199]
#### Problem description
We can have a top up navigation button so that the navigation will be easier and so that the app follows design guideline  
#### Steps to reproduce the problem
A new UI Feature
#### Expected behavior
the newly added up button should help in navigation and building up the activity stack (if the app is opened using a intent)

![image](https://user-images.githubusercontent.com/29946262/54084013-7cfedc00-4351-11e9-82a3-7b5975d639d9.png)

**Comment by lakshyagupta21** [comment]
Issue is already raised for this enhancement #108, so closing this issue.
