### ISSUE TITLE
No touch feedback for forms  

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#202]
#### Software and hardware versions 
Samsung J8

#### Problem description
Currently, when we click on any forms there is no touch feedback 
there should be a touch feedback i.e ripple when we clicked on any form

#### Steps to reproduce the problem
go to any recycler view screen and click on any form observe the behavior

#### Expected behavior
There should be user feedback when we touch on any form

**Comment by Chromicle** [comment]
@shobhitagarwal1612 @lakshyagupta21 can I work on this, thankyou!

**Comment by lakshyagupta21** [comment]
Sure go ahead.

**Comment by Chromicle** [comment]
@opendatakit claim
