### ISSUE TITLE
Statistics fragment does not scroll on rotating the screen

### ISSUE THREAD

**Issue by iamvasuh** [opendatakit/skunkworks-crow#204]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description

Statistics fragment does not scroll down when the device is in **landscape mode**.
Due to this issue, the whole activity is not visible to the user.

#### Steps to reproduce the problem
![simple1](https://user-images.githubusercontent.com/42612183/54154206-5d59d780-4467-11e9-876b-8c7d08a19c45.gif)

#### Expected behavior

When tapped on the "Statistics" tab , and the phone is in landscape mode,
the user should be able to view the whole activity by scrolling up or down.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by iamvasuh** [comment]
@shobhitagarwal1612 @lakshyagupta21 can i work on this issue?

**Comment by lakshyagupta21** [comment]
@iamvasuh Please claim the issues before start working on the issues. This will avoid multiple people working on same ticket.

**Comment by iamvasuh** [comment]
@opendatakit-bot claim

**Comment by iamvasuh** [comment]
this issue can be closed now

**Comment by lakshyagupta21** [comment]
It will be closed automatically once PR is merged.

**Comment by iamvasuh** [comment]
> It will be closed automatically once PR is merged.

ok
