### ISSUE TITLE
Password is not hiding while entering the password

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#216]
#### Software and hardware versions 
Android Samsung j8

#### Problem description
While we entering the password the text should i.e it will show dots after entering each character

#### Steps to reproduce the problem
go to settings and enable set password and tap on set hotspot password and enter anything observe the behavior

#### Expected behavior
while entering the password it should hide after each character

**Comment by Chromicle** [comment]
Can I work on this

**Comment by lakshyagupta21** [comment]
Sure go ahead.

**Comment by shobhitagarwal1612** [comment]
@Chromicle Please finish the currently claimed issues before taking on this one. I hope you do understand the intention behind it.

**Comment by rob729** [comment]
@lakshyagupta21 @shobhitagarwal1612 Can I work on this issue?

**Comment by iadeelzafar** [comment]
Yes. You can claim this using the bot.

**Comment by rob729** [comment]
Thanks @iadeelzafar

**Comment by rob729** [comment]
@opendatakit-bot claim

**Comment by Chromicle** [comment]
> @lakshyagupta21 @shobhitagarwal1612 Can I work on this issue?

I already asked to work on this all I already send PRs for which I am working on

**Comment by shobhitagarwal1612** [comment]
@Chromicle The issue was unclaimed and was available for anyone to take. It is encouraged to start working on an issue only if you are assigned to it otherwise this happens.

**Comment by lakshyagupta21** [comment]
@Chromicle, Sorry I know that you raised this issue and you had shown interest in working on this but our intention is always to help new contributors to make their first contribution so that they can feel comfortable with the project. And as you can see that this issue is labeled as `good first issue` and so I think it would be good if someone new can pick this up. Hope you understand our intention.

**Comment by nishontan** [comment]
@opendatakit-bot claim
