### ISSUE TITLE
Stop dialog is still shown if hotspot is not enabled.

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#223]
#### Software and hardware versions 
Android v7.1

#### Problem description
If user doesn't trigger hotspot from the settings screen, then it still asks  `stop sending` when the user taps back button.

#### Steps to reproduce the problem
1. Tap on 'Send' button.
2. Select forms to send.
3. Tap on 'Send'
4. Tap on 'Settings'
5. Don't enable from the settings screen opened (press back button)
5. A screen shows message 'Problem in creating hotspot'
6. Press the back button
7. Dialog is shown to notify a user to stop sending the forms
#### Expected behaviour
No dialog should be shown to the user if hotspot not started.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
![1](https://user-images.githubusercontent.com/18495162/54877172-ee09bd80-4e40-11e9-8477-1923dcb6b8da.gif)

**Comment by nishontan** [comment]
@opendatakit-bot claim

**Comment by Chromicle** [comment]
If I already enabled the location still the confirmation dialoge is coming to me 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48018942/55040978-e7ea2b80-5050-11e9-9cb8-0be400998108.gif)
