### ISSUE TITLE
When Writing Hotspot Password, OK Button Should Be Disabled Until 8 Chars

### ISSUE THREAD

**Issue by iadeelzafar** [opendatakit/skunkworks-crow#233]
#### Software and hardware versions 
Galaxy Nexu API 24

#### Problem description
When Writing Hotspot Password, OK Button Should Be Disabled Until 8 input chars by the user.
Currently, the user is allowed to click the "OK" button even when chars<8 and a toast message appears afterwards showing the error. This toast message can also be removed with these changes.
#### Steps to reproduce the problem
1- Go to settings
2- Click Hotspot Password
3- Write characters less than 8.
4- Click OK
#### Expected behavior
OK button should be disabled until 8 input chars and enabled once the user has inputted 8 chars.

This issue can be solved using a TextWatcher.

#### GIF
<img src="https://user-images.githubusercontent.com/36811908/55350579-dd5ae680-54d5-11e9-88a8-93b6840c0502.gif" height="700" width="394">

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by iadeelzafar** [comment]
This is a good issue for new contributors to start getting familiar with the codebase. This is up for grabs.

**Comment by rohitnitk** [comment]
Which one is the java class to handle password related stuff?

**Comment by rohitnitk** [comment]
it seems that a common interface of dialog is used for all the four options in Setting, so changing the dialog for Password will affect that for other three (edited) , I'm working upon it

**Comment by Chromicle** [comment]
@rohitnitk No, every one has separate functionality have a look on the method  `showPasswordDialog` in `SettingsPreferance.java` you can see the alert dialogue you can change it there

**Comment by iadeelzafar** [comment]
@rohitnitk claim this issue, if you're working on. So that no one else gets confused.

**Comment by Chromicle** [comment]
@rohitnitk are you still working on this if yes please claim this issue using `@opendatakitbot claim` or else I will claim it

**Comment by rohitnitk** [comment]
@opendatakit-bot  I'm working on this issue

**Comment by Chromicle** [comment]
as I commented above, just type this line `@opendatakitbot claim` to claim in comment section

**Comment by rohitnitk** [comment]
@opendatakit-bot claim

**Comment by rohitnitk** [comment]
@opendatakit-bot claim --force

**Comment by jhbiggs** [comment]
@opendatakit-bot claim

**Comment by jhbiggs** [comment]
@opendatakit-bot claim --force

**Comment by devanshi7799** [comment]
@opendatakit-bot claim

**Comment by Chromicle** [comment]
you can claim the issue by `@opendatakit-bot claim --force`

**Comment by devanshi7799** [comment]
@Chromicle thanks!

@opendatakit-bot claim --force

**Comment by Chromicle** [comment]
@devanshi7799 Welcome to open data kit I hope you will learn new stuff here 😄

**Comment by devanshi7799** [comment]
@Chromicle Looking forward to it☺ Thank you so much

**Comment by manit-alokbatham** [comment]
@opendatakit-bot claim
