### ISSUE TITLE
When back pressed on set hotspot password it is not going to back and does not open soft keyboard automatically

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#241]
#### Software and hardware versions 
Android Samsung j8

#### Problem description
when we pressed back button instead of cancel button the alert dialog should be canceled but it is not coming back 
when the alert dialogue is opened the soft keyboard should open automatically but it does not happen

#### Steps to reproduce the problem
Go to the settings screen
press the Set Hotspot password
instead of cancel button use the back button  to cancel alert dialogue
see the behavior 

#### Expected behavior
when we pressed back it should be canceled and we will get into the settings to screen only
when we clicked on set hot spot password soft keyboard should open automatically

**Comment by Chromicle** [comment]
@opendatakit-bot claim

**Comment by Chromicle** [comment]
@opendatakit-bot I already made a pull request on it #243 it has to be review

**Comment by lakshyagupta21** [comment]
@Chromicle Thanks for raising the PRs, I will go through the PR once more and do the testing so that it doesn't break anything else.
