### ISSUE TITLE
The RecyclerView content expand their height after each search query

### ISSUE THREAD

**Issue by rohitnitk** [opendatakit/skunkworks-crow#242]
#### Software and hardware versions 
Android 8.1, device used Redmi note 5

#### Problem description
The height of each item in Recycler View under the 'Filled form' and 'Blank forms' increases down each time  a query is entered in search bar
#### Steps to reproduce the problem
Press SEND button at home screen,
Start typing in search bar, hit enter. Do this again and again, you will see the size of item increases.

#### Expected behavior
The size should remain same

<br /> <h2 align="center" style="bold"><b> Expanded </b>  </p>
![Screenshot_2019-04-08-18-28-10-669_org odk share 1](https://user-images.githubusercontent.com/46598745/55726143-bdbf4300-5a2c-11e9-9167-b2046e92a0f6.png)
<br /> 
<br /><br /><h2 align="center" style="bold"><b> Original Size </b>  </p>
![Screenshot_2019-04-08-18-28-31-199_org odk share 1](https://user-images.githubusercontent.com/46598745/55726159-c4e65100-5a2c-11e9-9e74-b13eac05b26f.png)

**Comment by rohitnitk** [comment]
Update: The size increases only when the entered character is matched to any of the item name's chars

**Comment by Chromicle** [comment]
@rohitnitk that is occurring due to when the character entered does not match to one of the forms then recycler view became empty so the space is not appearing
It's not a main thing to resolve.

**Comment by iadeelzafar** [comment]
@rohitnitk I think you should work with a empty view. That'd resolve this issue.

**Comment by rohitnitk** [comment]
BTW why it need to expand at all?

**Comment by Chromicle** [comment]
As we are using same layout for all filled and blank forms
We are updating according to that are we are hiding some of the text views the space is allocated is remains same in recycle view 
I am facing the issue but I am not experiencing so much gap as much as shown in pr templete

**Comment by rohitnitk** [comment]
![Screenrecorder201905051524](https://user-images.githubusercontent.com/46598745/57192220-b025ac00-6f4b-11e9-8cfe-2cc5b1c1da05.gif)

**Comment by manit-alokbatham** [comment]
@lakshyagupta21 

I worked on this issue today and this issue has been fixed. when PR #321 will be merged to master then i'll create a PR for this issue. I checked fix on 3 devices and it's now working as expected.

**Comment by manit-alokbatham** [comment]
![RV_#242](https://user-images.githubusercontent.com/58147504/69897202-2cf7f780-136e-11ea-91f0-81f31c643fb2.gif)


Final fix with minimum changes and no impacted areas, ready to merge. waiting for #321 to merge then I'll create a PR for this.

**Comment by manit-alokbatham** [comment]
@lakshyagupta21 

I've created a pull request #322 for #242 (this) issue fix.
