### ISSUE TITLE
When there is empty list hide search and sort icons

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#249]
#### Software and hardware versions 
Android samsung J8

#### Problem description
When there is an empty list(I.e empty recycle view) now currently the search and sort icons are there 
There is no need those icons when empty list  

#### Steps to reproduce the problem
Make recycle view to empty (i.e delete all forms)
see the behaviour

#### Expected behavior
When there is a empty recycle view icons should hide

**Comment by lakshyagupta21** [comment]
I don't think that icons should be set hidden when the list is empty.

**Comment by lakshyagupta21** [comment]
If its a icon we don't do anything and if its a button then we disable them.

**Comment by Chromicle** [comment]
> I don't think that icons should be set hidden when the list is empty.

user may confuse that what is the need of the icons if there is a empty list

**Comment by lakshyagupta21** [comment]
No, I don't think from those icons users will be confused if list is empty then user is expected to know that there is nothing you can search or sort from list. 

I didn't see any app where such confusion happened to me. If any user reports this then we will look into it later but for now I think we can close this.

**Comment by Chromicle** [comment]
Ok then! I am closing this, the reason I added this issue was when I show this app to one of my friends he said that what is need of icons if there a empty list
