### ISSUE TITLE
[Refactor] Replace the layout default height and weight using style.xml

### ISSUE THREAD

**Issue by huangyz0918** [opendatakit/skunkworks-crow#254]
#### Problem description
We have many layout elements like:

```xml
android:layout_width="match_parent"
android:layout_height="wrap_content"
```
We can use some common attrs in `style.xml` to replace them like:

```xml
style="mMatchParentWidth"
```

Other common width and height attributes are the same.
We have two advantages related to this refactor:

- Make the code easier to read.
- Make the code easier to maintain, we only need to modify the `style.xml` if we want to change something. 

#### Other information 
@opendatakit-bot claim

**Comment by Chromicle** [comment]
Yeah, it's a great issue but we are using almost same padding and margin if we define for that also means it will be great
