### ISSUE TITLE
Add empty view when no device present

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#278]
### Problem description
It's kind of confusing what to do when there are no Bluetooth devices available in the nearby area. There is one refresh button present with no message saying that 'No devices are available in the nearby area.'
#### Steps to reproduce the problem
1. tap on 'receive'
2. Select 'Bluetooth'
3. Wait for devices to show up. 
#### Expected behavior
There should be some view displayed with some meaningful message maybe like 'No devices are available. Tap Refresh to search again.' And till the time it searches for the bluetooth devices there should be some undeterminate progress bar present over the screen with refresh button disabled, and when its done with the searching depending on the failed or success status of devices found refresh button is enabled and empty view is displayed.
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lakshyagupta21** [comment]
@huangyz0918 I think you already added a progress bar in https://github.com/opendatakit/skunkworks-crow/pull/272, so no need to add it again.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim , @lakshyagupta21 sure.
