### ISSUE TITLE
Device present in available list of devices

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#282]
#### Software and hardware versions 
Android 9 and Android 7.1

#### Problem description
When devices switch off the Bluetooth, it is still present in receiver's devices even after refreshing the list it doesn't get removed.
#### Steps to reproduce the problem
1. Start sender with `Bluetooth` as a medium
2. Start receiver and search for devices
3. Wait for receiver to scan the devices
4. Now sender's device is shown in the list
5. Disconnect the sender and switch off the Bluetooth.
6. Tap on `Refresh` on receiver's device
#### Expected behavior
The device list should be cleared when the refresh button is tapped and it should show the list only when it gets the new set of available devices(It should clear the previous list, currently it appends new available devices to same list)

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by huangyz0918** [comment]
@opendatakit-bot claim
