### ISSUE TITLE
add a user guide section in about page

### ISSUE THREAD

**Issue by huangyz0918** [opendatakit/skunkworks-crow#289]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
In current `AboutActivity`, we only have an `open source licenses` section, I think we can add a guide section as well, it well be good for users to check if they have some issues using our application, no need to check `README.md` every time.

#### Other information 
@opendatakit-bot claim

**Comment by naman653** [comment]
@opendatakit-bot claim

**Comment by naman653** [comment]
@lakshyagupta21 should I work on this?

**Comment by lakshyagupta21** [comment]
@naman653 Sure go ahead. You can work on any unassigned issue, claim it and then start working on it.
