### ISSUE TITLE
App not starting if permission is denied

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#295]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
App doesn't start if application doesn't have storage permission.

#### Steps to reproduce the problem

1. Reset the app if already installed.
2. Install the app.
3. Deny the storage permission.
4. Open app again.
5. Mark the checkbox selected.
6. Again deny the storage permission.
7. Try opening the app again, it won't start.
#### Expected behavior
App should ask user to enable the permissions(through dialog box) from the app settings.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
I can apply our strategy in the #286
