### ISSUE TITLE
Add auto-label bot

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#305]
#### Problem description
Add auto-label bot for automatically labeling prs.
By adding auto label bot so, we can list out type of PRs and it is so helpful for new contributors to know about the repo

**Comment by lakshyagupta21** [comment]
> By adding auto label bot so, we can list out type of PRs and it is so helpful for new contributors to know about the repo

@Chromicle Just a couple of questions regarding this. How do you plan to do this and what do you mean by list out type of PRs? How it will be helpful for new contributors?

**Comment by Chromicle** [comment]
yeah, @lakshyagupta21 for example if we put this as PR title `fix: fixed Bluetooth issue in receiving forms`  so, the auto label bot detects the type and it will label it as a fix,  so, whatever the type it will label as that
so, that the new contributors can list out what are the previous PRs on ex: `doc` so, they can get the good reference to solve the issue

**Comment by huangyz0918** [comment]
Apart from this auto-labeling feature, @lakshyagupta21 can you add some Collect labels in skunkworks-crow? It seems we missed some labels like `needs review` and `needs testing`, so if we use the `@opendatakit-bot label 'needs review'` there will be an error.
