### ISSUE TITLE
Stop turning off bluetooth after sharing forms when initial state is on

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#306]
#### Software and hardware versions 
Android Samsung J8

#### Problem description
currently, after sending forms Bluetooth is turning off but when user is using Bluetooth before sharing forms but after sharing forms it is turning off so before turning off Bluetooth check initial state and if it is on leave that if it is off make it off

#### Steps to reproduce the problem
Share any form and check initial and after state

#### Expected behavior
if Bluetooth is on leave that if it is off make it off after sharing forms

**Comment by naman653** [comment]
I would like to work on this issue.

**Comment by lakshyagupta21** [comment]
@naman653 Welcome to the community,  sure go ahead you can pick any of the unassigned open issues.

**Comment by naman653** [comment]
@opendatakit-bot claim
