### ISSUE TITLE
After form transfer status on Main screen is not updated correctly

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#309]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
Whenever any instance form transfer happens, there is some discrepancy in reviewed and unreviewed status on the main screen.
#### Steps to reproduce the problem
1. Download all the available forms(at least two is needed to distinguish the status) from the default server on both sender and receiver.
2. Create one instance of Collect-Location form in one device and send it to the other.
3. Go on home screen and check the status of unreviewed form, it shows the unreviewed counter of `All widgets` form.
#### Expected behavior
It should show the unreviewed status for Collect-location form.
#### Other information 
There is some code problem in FormsAdapter class where we're querying the instances and transfer table.
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by manit-alokbatham** [comment]
@opendatakit-bot claim

**Comment by chidauri** [comment]
@lakshyagupta21 Similar problem exists for sent and received forms too :(

**Comment by Chromicle** [comment]
@opendatakit-bot claim
