### ISSUE TITLE
Remove hardcoded dimens from xml layout files

### ISSUE THREAD

**Issue by KAbhijeet2105** [opendatakit/skunkworks-crow#326]
**Software and hardware versions** 
Android 9.0 (Pie)

 **Problem description**
Remove hardcoded dimen resources from xml layout files.

 **Steps to reproduce the problem**
Go through the project codebase and layout files(i.e xml layout files)

 **Expected behavior**
Remove hardcoded dimen(eg. 16dp) resources from xml layout files.
Move hardcoded dimension(ex: 16dp) to dimens.xml file

**Other information** 
 suggestions on how to fix it...
Move hardcoded dimension(ex: 16dp) to dimens.xml file

**Comment by Chromicle** [comment]
Hello, @KAbhijeet2105 thank you for raising the issue 
As this issue is related to coding style it is good to know everyone's opinions so, make one thread in the slack channel and discuss there 😄

**Comment by KAbhijeet2105** [comment]
@opendatakit-bot claim

**Comment by KAbhijeet2105** [comment]
@opendatakit-bot claim --force.
