### ISSUE TITLE
App Crashes on Selecting any Finalized form or Pressing Send

### ISSUE THREAD

**Issue by sarrocks1** [opendatakit/skunkworks-crow#331]
Android v9, device used Nokia 7 Plus.

Problem description- The Skunkworks-crow app crashes on selecting any Finalized form on the Home Screen.No such issues with non finalized forms. App also crashes on pressing Send Button.

Steps to reproduce the problem- 
1.Open the app
2.Select any Finalized form on the homepage **OR** Click on Send Button
3.App Crashes

Expected behavior - Tapping on the form should open the screen with 4 tabs , statistics, sent, received, and reviewed.

**Comment by Chromicle** [comment]
Welcome to opendata kit and thanks for raising issue but it is Duplicate of #323 and I already sent PR for that it will be merge soon

**Comment by sarrocks1** [comment]
Ok , Thanks a lot I am closing this
