### ISSUE TITLE
Improving UI of application

### ISSUE THREAD

**Issue by maharishi1** [opendatakit/skunkworks-crow#359]
#### Software and hardware versions 
Android 7, Lenovo K6Note

#### Problem description
The UI not really attractive. Like button, text and the arrangement of permission icon like Wi-Fi, Bluetooth etc.

#### Steps to reproduce the problem
open the application and go to the other page.

#### Expected behaviour
instead of rectangle button, other shape will be better. And spinner for Wi-Fi Bluetooth or arrangement of icon in right way

@opendatakit-bot claim

**Comment by Chromicle** [comment]
Hello, @maharishi1 thanks for raising the PR, but it looks like a duplicate of #334 you can discuss there if you have any new ideas 
if you don't have any queries please close this issue and discuss there

**Comment by maharishi1** [comment]
OK ......actually I am new here....
