### ISSUE TITLE
Home screen form status not updated

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#86]
Status shown on home screen not updated when user taps on back button after reviewing the form but it gets updated in statistics screen.

Noticed in #74

**Comment by jddeep** [comment]
@lakshyagupta21 i would like to work on this. Shall i? Kindly assign it. Thanks

**Comment by lakshyagupta21** [comment]
Sure but can you check once whether this issue is reproducible or not.

**Comment by shobhitagarwal1612** [comment]
Unable to reproduce
